# Generated by Django 2.1.7 on 2019-03-07 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 7, 21, 19, 25, 851161, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
